### ISSUE TITLE
Eclipse Marsで「テスティングペアを開く」で無反応

### ISSUE THREAD

**Issue by nabedge** [kompiro/quick-junit#3]
適当な実装クラスを右クリックして「テスティングペアを開く」をしても無反応です。
.metadata/.log にはこんなのが出ました。

```
!ENTRY org.eclipse.ui 4 0 2015-08-26 18:56:11.419
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
    at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.getCurrentProject(OpenTestingPairAction.java:232)
    at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.findCurrentProject(OpenTestingPairAction.java:226)
    at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.findPairTypes(OpenTestingPairAction.java:204)
    at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.run(OpenTestingPairAction.java:190)
    at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

試用しているeclipseは
Eclipse Java EE IDE for Web Developers.
Version: Mars Release (4.5.0)
Build id: 20150621-1200
です。

QuickJunitは
0.7.0.201204240825
です。

**Comment by nabedge** [comment]
念のため、 eclipse.org からダウンロードした新規の
Eclipse for Java Developers (JavaEEじゃないほう) に、
quick-junitをsource forgeのupdate siteからインストールして使ってみましたが、
結果は上と同様でした。

```
!ENTRY org.eclipse.ui 4 0 2015-08-29 16:20:23.922
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
        at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.getCurrentProject(OpenTestingPairAction.java:232)
        at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.findCurrentProject(OpenTestingPairAction.java:226)
        at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.findPairTypes(OpenTestingPairAction.java:204)
        at junit.extensions.eclipse.quick.internal.action.OpenTestingPairAction.run(OpenTestingPairAction.java:190)
        at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
        at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by nabedge** [comment]
Quick JUnit はEclipse4.x(luna,mars)以降に対応する予定は無いのでしょうか？
しかしそれにしては https://github.com/kompiro/quick-junit/pull/2 においても若干の議論がなされており（1年経ってはいますが）、forkしてMars対応版を作り始めるべきかどうか決めあぐねております。
ちなみにもしも私がやるときはMars以降だけをターゲットにするつもりではおりますが。
